### PR TITLE
Fix app creation in source.wsgi, add regression test

### LINKED ISSUE #6741: SI issuing a 500 error and then timing out on `develop`
## Description
The SI  is failing to start from the `develop` branch, first failing with a 500 error and the log messages below (with logs enabled, and then just timing out:
```
[Fri Feb 03 21:37:34.589966 2023] [wsgi:info] [pid 1330:tid 118957187065600] [remote 127.0.0.1:51894] mod_wsgi (pid=1330, process='source', application='localhost|'): Loading Python script file '/var/www/source.wsgi'.
[Fri Feb 03 21:37:34.591940 2023] [wsgi:error] [pid 1330:tid 118957187065600] [remote 127.0.0.1:51894] mod_wsgi (pid=1330): Failed to exec Python script file '/var/www/source.wsgi'.
[Fri Feb 03 21:37:34.592605 2023] [wsgi:error] [pid 1330:tid 118957187065600] [remote 127.0.0.1:51894] mod_wsgi (pid=1330): Exception occurred processing WSGI script '/var/www/source.wsgi'.
[Fri Feb 03 21:37:34.593310 2023] [wsgi:error] [pid 1330:tid 118957187065600] [remote 127.0.0.1:51894] Traceback (most recent call last):
[Fri Feb 03 21:37:34.593658 2023] [wsgi:error] [pid 1330:tid 118957187065600] [remote 127.0.0.1:51894]   File "/var/www/source.wsgi", line 11, in <module>
[Fri Feb 03 21:37:34.593894 2023] [wsgi:error] [pid 1330:tid 118957187065600] [remote 127.0.0.1:51894]     from source import app as application
[Fri Feb 03 21:37:34.594012 2023] [wsgi:error] [pid 1330:tid 118957187065600] [remote 127.0.0.1:51894] ImportError: cannot import name 'app' from 'source' (/var/www/securedrop/source.py)
```

## Steps to Reproduce

- set up a prod VM instance on `.2.5.1` 
- build packages from `develop` with `make build-debs`
- step through the upgrade scenario to apply said debs

## Expected Behavior
- system is upgraded cleanly and SI and JI functionality is available

## Actual Behavior
- JI is available, SI errors out with an initial 500 error as described.

## Comments

This looks to have been introduced in https://github.com/freedomofpress/securedrop/pull/6563, specifically in the change in https://github.com/freedomofpress/securedrop/blob/c9e2a7a61c486e38e4fcf06b6196b59a115ce152/securedrop/source.py#L6 . Since `app` is now defined only within the `__name__ == 'main'` block, it isn't defined when run via WSGI (as opposed to directly within the dev env).

### PR DESCRIPTION
**Pull request by legoktm**
## Status

Ready for review

## Description of Changes

* Fix app creation in source.wsgi, add regression test
* Use correct permissions when installing source.wsgi.logging in staging
* Add basic testinfra smoke tests to verify SI and JI are up

See individual commit messages for further detail.

Fixes #6741.

## Testing

How should the reviewer test this PR?

* [ ] CI passes, including staging build
* [ ] Revert the changes to source.py, run the newly added test_wsgi, verify it fails (i.e. it catches the regression)
* [ ] Run `make build-debs`, install on a staging/prod environment, verify source interface works. Then run testinfra checks and verify they pass.

## Deployment

Any special considerations for deployment? No, this fixes regressions that were never released.

## Checklist

- [ ] Linting (`make lint`) and tests (`make test`) pass in the development container
- [ ] I have written a test plan and validated it for this PR

### CODE REVIEW

**Comment by legoktm** [comment]
Verified the source.py fix works in prod (and discovered #6743 along the way). Now figuring out why test_wsgi is passing locally and failing in CI and if we can also do a testinfra check too.

**Comment by legoktm** [comment]
staging failure is because hitting the smoke test against SI is giving a HTTP 500 Internal Server Error. :(

**Review by zenmonkeykstop — APPROVED** [review]
Changes look good, SI available in Qubes staging, and testinfra is green locally. LGTM
