### PR TITLE
Improve pluralization of translated strings

### LINKED ISSUE #5566: A few UI strings containing numeric variables can't be pluralized by translators
## Description

It's been [pointed out](https://forum.securedrop.org/t/arabic-plurals-in-securedrop/1375) that some of our strings containing numeric variables aren't marked for translation with `ngettext`, meaning that translators can't properly pluralize them:

- https://weblate.securedrop.org/translate/securedrop/securedrop/ar/?checksum=1ca223a1a619dfb8
- https://weblate.securedrop.org/translate/securedrop/securedrop/ar/?checksum=d483164b7d74e4b4
- https://weblate.securedrop.org/translate/securedrop/securedrop/ar/?checksum=45fb940361536e6e

Compare their presentation in Weblate to that of a string marked with `ngettext`, which lets translators provide plural forms: https://weblate.securedrop.org/translate/securedrop/securedrop/ar/?checksum=e2559e4b13921ef6

## Comments

We just need to use `ngettext` for these instead of `gettext`.

### PR DESCRIPTION
**Pull request by rmol**
## Status

Ready for review

## Description of Changes

Switch a few strings containing numeric variables to `ngettext` from `gettext`, to ensure they can be properly translated. Use "num" more consistently as the placeholder for numeric variables in strings marked with `ngettext`, to make things easier for translators.

Fixes #5566.

## Testing

- `git checkout -b more-plurals origin/more-plurals`
- `make translate`
- Choose a test language, e.g. `de_DE` and edit its `.po` file (`securedrop/translations/de_DE/LC_MESSAGES/messages.po`) to find the updated source strings, remove the `fuzzy` markers, and correct the placeholder names.
- In that `.po` file's directory, run `msgfmt messages.po`.
- Run `make dev`.
- Visit the journalist interface, switch to your test language, and ensure that the strings are being translated correctly:
  - Visit the admin page to add a new user. 
    - Enter a HOTP secret a few characters long.
    - Enter less than three characters in the username field.
    - Enter more than 100 characters in the first and last name fields.
    - Pressing add user should result in properly-translated error messages. 
  - Visit the source list and verify that the document, message, and unread counts are being properly translated. You'll need to submit a single file and document as a new source to test singular translations.
  - Delete a single source from the source list. The `{num} collection deleted` message should be properly translated.
  - Delete more than one source from the source list. The `{num} collections deleted` message should be properly translated.
  - Delete a single source submission. The `Submission deleted` flash message should be properly translated.
  - Delete more than one source submission. The `{num} submissions deleted` flash message should be properly translated.

## Deployment

The updated strings will need to be translated at the next release. Until then, they'll always appear in English. 

### If you made changes to the server application code:

- [ ] Linting (`make lint`) and tests (`make test`) pass in the development container

### If you made non-trivial code changes:

- [x] I have written a test plan and validated it for this PR

### CODE REVIEW

**Comment by emkll** [comment]
Thanks @rmol test plan as described is passing, however encountered an error locally prior to updating the translations. Without the translations generated, an error is thrown (likely due to the name of the variables changing) but is being caught by the API error handler in  https://github.com/freedomofpress/securedrop/blob/more-plurals/securedrop/journalist_app/__init__.py#L92:
```
  File "/home/user/src/securedrop/securedrop/journalist_app/__init__.py", line 92, in _handle_http_exception
    handler = list(app.error_handler_spec['api'][error.code].values())[0]
AttributeError: 'KeyError' object has no attribute 'code'
```
Error handling here might warrant further investigation and/or we we consider strings as as part of this PR to support multiple languages in develop (prior to merging string changes). Right now, on this branch, using any other language than English on the source list of the journalist interface will result in error 500.

**Comment by rmol** [comment]
I've updated the translations. There should be no more errors because of the changed strings, and in the next translation period, translators should only have to update the strings newly marked with `ngettext`, and only in the languages with multiple plural forms.

**Comment by emkll** [comment]
(rebased on latest develop)

**Comment by emkll** [comment]
Looks like translation tests are failing after the rebase on latest `develop`, it is likely due to the Tor Browser update introduced in https://github.com/freedomofpress/securedrop/pull/5578

**Comment by rmol** [comment]
I think it was actually my [fix for Redis dump file version incompatibility](https://github.com/freedomofpress/securedrop/pull/5558). The `translation-test` script never sets `REPOROOT`, breaking the `run-redis` function and causing the [Redis connection errors](https://app.circleci.com/pipelines/github/freedomofpress/securedrop/1191/workflows/d02c0ffa-20c3-4520-91f3-37d87edcbc50/jobs/45767) and subsequent Selenium timeouts. I added a commit to make sure it does get set in `dev-deps` before it's used, and so far so good.

**Comment by rmol** [comment]
Nope, after rebasing, also had problems running the newly-type-hinted `i18n_tool.py` under Python 2 (ahem), so updated the translation test job to use Python 3. About time. Translation tests are now [passing](https://app.circleci.com/pipelines/github/freedomofpress/securedrop/1208/workflows/ad11838d-e64f-4472-a5ec-6ccdfbcba477/jobs/45863).

**Review by emkll — COMMENTED** [review]
Thanks @rmol looks good to me, went through the diff and the functional test of the translations:

- [x] Visit the journalist interface, switch to your test language, and ensure that the strings are being translated correctly:
- [x] Enter a HOTP secret a few characters long.
- [x] Enter less than three characters in the username field.
- [x]  Enter more than 100 characters in the first and last name fields.
- [x]  Pressing add user should result in properly-translated error messages. 
- [x] Visit the source list and verify that the document, message, and unread counts are being properly translated. You'll need to submit a single file and document as a new source to test singular translations.
- [x] Delete a single source from the source list. The `{num} collection deleted` message should be properly translated.
- [x] Delete more than one source from the source list. The `{num} collections deleted` message should be properly translated.
- [x] Delete a single source submission. The `Submission deleted` flash message should be properly translated.
- [x] Delete more than one source submission. The `{num} submissions deleted` flash message should be properly translated.

I've noticed that for `cs`, `ro`, `ru` and `sk`, the `fuzzy` attribute is preserved in the translations of the strings that were touched. was this intentional?

**Review by emkll — APPROVED** [review]
Approving based on previous review, as discussed fuzzy translation for those four languages is expected.
