### ISSUE TITLE
cffi and argon2_cffi needs update for buiding in Ubuntu 20.04

### ISSUE THREAD

**Issue by kushaldas** [freedomofpress/securedrop#5453]
## Description

The current values fail to build on `Ubuntu Focal 20.04`.

```
  wrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/usr/include/ffi -I/usr/include/libffi -I/usr/include/python3.8 -c c/_cffi_backend.c -o build/temp.linux-x86_64-3.8/c/_cffi_backend.o", "    c/_cffi_backend.c: In function ‘b_do_dlopen’:", "    c/_cffi_backend.c:4197:31: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]", "     4197 |         *p_printable_filename = PyText_AsUTF8(s);", "          |                               ^", "    c/_cffi_backend.c: In function ‘b_callback’:", "    c/_cffi_backend.c:5911:5: warning: ‘ffi_prep_closure’ is deprecated: use ffi_prep_closure_loc instead [-Wdeprecated-declarations]", "     5911 |     if (ffi_prep_closure(closure, &cif_descr->cif,", "          |     ^~", "    In file included from c/_cffi_backend.c:15:", "    /usr/include/x86_64-linux-gnu/ffi.h:334:1: note: declared here", "      334 | ffi_prep_closure (ffi_closure*,", "          | ^~~~~~~~~~~~~~~~", "    In file included from c/cffi1_module.c:20,", "                     from c/_cffi_backend.c:7370:", "    c/call_python.c: In function ‘_get_interpstate_dict’:", "    c/call_python.c:20:30: error: dereferencing pointer to incomplete type ‘PyInterpreterState’ {aka ‘struct _is’}", "       20 |     builtins = tstate->interp->builtins;", "          |                              ^~", "    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1", "
 
```

The following two packages should be upgraded:

- cffi == 1.14.0
- argon2_cffi == 20.1.0

This is part of #4768 for the package build on Focal

**Comment by kushaldas** [comment]
- cffi == 1.14.0
- argon2_cffi == 20.1.0

These two versions can be built on xenial too. I will have to submit a diff-review too.
